#define HAVE_INTTYPES_H 1
#define HAVE_SELECT 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1

#define VERSION "4.24"

#define EV_ASYNC_ENABLE 0
#define EV_CHILD_ENABLE 0
#define EV_SIGNAL_ENABLE 0

/*
EV_CHECK_ENABLE
EV_CHILD_ENABLE
EV_CLEANUP_ENABLE
EV_EMBED_ENABLE
EV_FORK_ENABLE
EV_IDLE_ENABLE
EV_PERIODIC_ENABLE
EV_PREPARE_ENABLE
EV_STAT_ENABLE
EV_WALK_ENABLE
EV_watchertype_ENABLE
*/
